name: leazkart_app
description: The official mobile application for leazkart.


publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.0-165.1.beta <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  pin_code_fields: ^7.4.0
  # format date time
  intl: ^0.16.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/images/lklogoclear.png
    - assets/images/signin.png

  fonts:
    - family: Jost
      fonts:
       - asset: assets/fonts/Jost-Regular.ttf
         weight: 300
       - asset: assets/fonts/Jost-Medium.ttf
         weight: 400
       - asset: assets/fonts/Jost-SemiBold.ttf
         weight: 500
       - asset: assets/fonts/Jost-Bold.ttf
         weight: 600
       - asset: assets/fonts/Jost-Black.ttf
         weight: 700



